### ISSUE TITLE
new command /rb info

### ISSUE THREAD

**Issue by L3thalBunny** [rkubik/RaidBoss#12]
Command returns health (and other optional stats) of raidboss currently under mouse focus to sender of command so admins can check on raidbosses while keeping mystery to players

**Comment by rkubik** [comment]
Fixed in v2. I'll leave this issue open for you to reply with any other stats needed.

![untitled](https://user-images.githubusercontent.com/927179/30148143-554d1490-935f-11e7-88f9-44a18c243511.png)

**Comment by rkubik** [comment]
Usage:

```
# Print all RB's within a 20 block radius
/rb info
# Print all RB's within a 10 block radius
/rb info 10
```

**Comment by rkubik** [comment]
Closing as fixed, any additional requirements can be opened against v3.
