### ISSUE TITLE
config variable "knockback" inaccurately labelled

### ISSUE THREAD

**Issue by L3thalBunny** [rkubik/RaidBoss#17]
Knockback speaks to the sword's ability to pushback where as the BOW's ability to push back is called "punch". Since the config value only alters the bow's ability, it should be called "punch" or something along the lines

**Comment by rkubik** [comment]
It disables both knockback and punch. We could separate it in v2 or v3.

**Comment by L3thalBunny** [comment]
k then it's a bug cause I been watching these guys with knockback on their swords pushing back the raidbosses. they go flying back with knockback 2
