### ISSUE TITLE
/rb spawn for non-configured raidboss throwing error

### ISSUE THREAD

**Issue by L3thalBunny** [rkubik/RaidBoss#24]
if only zombies are configured in config and player uses /rb spawn skeleton, "An internal error occurred while attempting to perform this command" is returned. should be "Skeleton Raid Boss is not configured"

**Comment by rkubik** [comment]
Fixed in build 36. http://reactor.faze.io:8087/job/Minecraft/job/Plugins/job/RaidBoss/36/
