### ISSUE TITLE
config states quantity of values loaded

### ISSUE THREAD

**Issue by L3thalBunny** [rkubik/RaidBoss#8]
eg.
Raod Boss config reloaded!
10 Monster deaths messages loaded
10 Monster kills messages loaded
4 Player kill messages loaded
8 Raid Bosses loaded

**Comment by rkubik** [comment]
Addressed in v2.

```
names:
- Name One
- Name Two
colors:
- BLUE
- BOLD
```

Then use `[monsterchat]` in the config messages.

**Comment by rkubik** [comment]
Completed in v2.
